name: Mi Primer Workflow de Automatizacion

on:
  push:
    branches:
      - main
    paths:
      - '**.js'

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verificar version de Node
        run: node -v
