name: Mi Primer Workflow de Automatizacion

on:
  push:
    branches:
      - main
    paths:
      - '**.js'

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Paso Uno - Imprimir mensaje en pantalla
        run: echo 'Hola CI/CD'
