name: Mi Primer Workflow de Automatizacion


on: [push]

jobs:

  saludar:

    runs-on: ubuntu-latest

    steps:
      - name: Paso Uno - Imprimir mensaje en pantalla
        run: echo 'Hola CI/CD'
